version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.1.1
  win: circleci/windows@2.2.0

jobs:
  backend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm test

  frontend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm test

  build_client:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm run build
      - run: cp -r client/build backend/dist/public

  build_backend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run build
    
  deploy:
    executor: heroku/default
    steps:
      - checkout:
          working_directory: backend
      - heroku/install
      - heroku/deploy-via-git:
          force: true
      
workflows:
  version: 2.1
  test_and_deploy_jobs:
    jobs:
    - backend
    - frontend
    - build_client:
        requires: 
          - frontend
    #       - build_backend
    # - build_backend:
    #     requires:
    #       - backend
    - deploy:
        requires: 
          - build_client
