version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.0
  win: circleci/windows@2.2.0
  react: thefrontside/react@0.2.0

jobs:
  backend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm test
  frontend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm test
  build_client:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm run build
      - run: cp -r client/build ../backend/dist/public

      # - store_artifacts:
      #     path: ./artifacts
  build_backend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run build
      # - run: cp -r artifacts backend/dist/public
      # - run: cd backend && curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/@CIRCLE_PROJECT_USERNAME/@CIRCLE_PROJECT_REPONAME/latest/artifacts \
      #   | grep -o 'https://[^"]*' \
      #   | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -

workflows:
  version: 2.1
  test_and_deploy_jobs:
    jobs:
    - backend
    - frontend
    - build_client:
        requires: 
          - frontend
          - build_backend
    - build_backend:
        requires:
          - backend
    - heroku/deploy-via-git:
        requires: 
          - build_client
        pre-steps:
          - run: cd backend $CIRCLE_ARTIFACTS
