version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.1.1
  win: circleci/windows@2.2.0

jobs:
  backend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm test

  frontend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm test

  build_client:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm run build
      # - run: cp -r client/build backend/dist/public

      - persist_to_workspace:
          root: ./
          paths:
            - client/build

  build_backend:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run build
    
  deploy:
    executor: heroku/default
    parameters:
      api-key:
        default: HEROKU_API_KEY
        type: env_var_name
      app-name:
        default: $HEROKU_APP_NAME
        type: string
      branch:
        default: main #$CIRCLE_BRANCH
        type: string
 
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/grid-editor
      - run: cp -a /tmp/grid-editor/client/build/. backend/dist/public/

      - run: git config user.email "bot@circleci.com" && git config user.name "Heroku Deployment Pipeline"
      - run: git add . && git commit -m \"deploy\"

      - heroku/install
      # - heroku/deploy-via-git:
      #     force: true
      # - when:
      #   condition: << parameters.maintenance-mode >>
      #   steps:
      #     - run:
      #         command: 'heroku maintenance:on --app << parameters.app-name >>'
      #         name: Turn ON maintenance mode.
      - run:
        # git subtree push --prefix backend $heroku_url << parameters.branch >>:master
          command: >
            heroku_url="https://heroku:$<< parameters.api-key >>@git.heroku.com/<<
            parameters.app-name >>.git"

            if [ -n "<< parameters.branch >>" ]; then
              git push $heroku_url `git subtree split --prefix backend << parameters.branch >>`:master --force              
            else
              echo "No branch or tag found."
              exit 1
            fi
      
workflows:
  version: 2.1
  test_and_deploy_jobs:
    jobs:
    - backend
    - frontend
    - build_client:
        requires: 
          - frontend
    - deploy:
        requires: 
          - build_client
