version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  backend:
      executor:
        name: node/default
        tag: '10.4'
      steps:
        - checkout
        - run: cd backend && npm test
workflows:
  version: 2.1
  backend_jobs:
    jobs:
      - backend
